# Generated by Django 2.0.1 on 2018-01-10 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180111_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 1, 10, 18, 43, 19, 438858, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 1, 10, 18, 43, 19, 438858, tzinfo=utc)),
        ),
    ]
